name: Build and Test Terraform Provider

on:
  push:
    branches:
      - feature/*  # Trigger on push to any branch starting with 'feature/'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Go (since you are building with Go)
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.21'  # Set the Go version

      # Step 3: Install Terraform (based on your Dockerfile)
      - name: Install Terraform
        run: |
          curl -o terraform.zip https://releases.hashicorp.com/terraform/1.6.6/terraform_1.6.6_linux_amd64.zip
          unzip terraform.zip
          sudo mv terraform /usr/local/bin/
          rm terraform.zip

      # Step 4: Set up Terraform Plugin Directory
      - name: Create Terraform plugin directory
        run: |
          mkdir -p ~/.terraform.d/plugins

      # Step 5: Build the mock server and provider
      - name: Build mock server and provider
        run: |
          cd mockserver && go mod init && go build -o mockserver
          cd ../terraform-provider-jsonendpoint && go mod tidy && go build -o terraform-provider-jsonendpoint

      # Step 6: Set up the plugin directory and copy the binary
      - name: Copy binary to plugin folder
        run: |
          mkdir -p ~/.terraform.d/plugins
          mv terraform-provider-jsonendpoint ~/.terraform.d/plugins/

      # Step 7: Verify the installation and binary setup
      - name: Verify Terraform binary and plugin
        run: |
          terraform version
          ls ~/.terraform.d/plugins
