name: Build, Test, and Push Docker Image

on:
  push:
    branches:
      - feature/*

env:
  IMAGE_NAME: tf-provider-demo
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.21'

      - name: Install Terraform
        run: |
          curl -o terraform.zip https://releases.hashicorp.com/terraform/1.6.6/terraform_1.6.6_linux_amd64.zip
          unzip terraform.zip
          sudo mv terraform /usr/local/bin/
          rm terraform.zip

      - name: Build mock server
        run: |
          cd mockserver
          go mod init mockserver || true
          go build -o mockserver

      - name: Build Terraform provider
        run: |
          cd terraform-provider-jsonendpoint
          go mod init example.com/demo/jsonendpoint || true
          echo 'replace github.com/local/jsonendpoint/provider => ./provider' >> go.mod
          go mod tidy
          go build -o terraform-provider-jsonendpoint

      - name: Set up Terraform plugin
        run: |
          mkdir -p ~/.terraform.d/plugins/example.com/demo/jsonendpoint/1.0.0/linux_amd64
          mv terraform-provider-jsonendpoint ~/.terraform.d/plugins/example.com/demo/jsonendpoint/1.0.0/linux_amd64/

      - name: Create terraform.rc
        run: |
          echo 'provider_installation {
            dev_overrides {
              "example.com/demo/jsonendpoint" = "~/.terraform.d/plugins/example.com/demo/jsonendpoint"
            }
            direct {}
          }' > ~/.terraformrc

      - name: Run Terraform Init
        run: |
          cd terraform-config
          terraform init

      # ---------- Docker Build and Push ----------

      - name: Log in to Docker Hub
        run: echo "${DOCKERHUB_TOKEN}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t $DOCKERHUB_USERNAME/$IMAGE_NAME:latest .

      - name: Push Docker image
        run: |
          docker push $DOCKERHUB_USERNAME/$IMAGE_NAME:latest
